# Dependabot Configuration
#
# References:
#
# - https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ci
      include: scope
    labels:
      - type:ci
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: '-'
    rebase-strategy: auto
    target-branch: next
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: build
      include: scope
    ignore:
      - dependency-name: '@storybook/react'
      - dependency-name: '@types/node'
      - dependency-name: '@types/styled-components'
      - dependency-name: styled-components
    labels:
      - type:build
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: '-'
    rebase-strategy: auto
    target-branch: next
    versioning-strategy: increase
